name: Terraform Storage Deploy

on:
  workflow_dispatch:

jobs:
  terraform-storage:
    name: Terraform Apply (Storage)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: Terraform Init
        working-directory: infra/infra-storage
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: infra/infra-storage
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: infra/infra-storage
        run: terraform apply -auto-approve tfplan

      - name: Mostrar outputs
        working-directory: infra/infra-storage
        run: terraform output

