name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'El entorno a desplegar'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: Terraform Init
        working-directory: infra/terraform
        run: |
          terraform init \
            -backend-config="bucket=bucket-stockwiz-tf" \
            -backend-config="key=${{ github.event.inputs.environment }}/terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: Terraform Plan
        working-directory: infra/terraform
        run: terraform plan \
          -var-file="${{ github.event.inputs.environment }}.tfvars" \
          -var="sender_email=${{ secrets.SENDER_EMAIL }}" \
          -var="app_password=${{ secrets.APP_PASSWORD }}" \
          -var="environment=${{ github.event.inputs.environment }}" \
          -out=tfplan

      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply -auto-approve tfplan

      - name: Obtener URL de la Lambda
        id: get-lambda-url
        working-directory: infra/terraform
        run: |
          echo "== Obteniendo URL del lambda =="
          LAMBDA_URL=$(terraform output -raw lambda_url)
          echo "URL obtenida: $LAMBDA_URL"
          echo "lambda_url=$LAMBDA_URL" >> $GITHUB_OUTPUT
          echo "==========="

      - name: Verificar URL
        run: |
          echo "La URL de la lambda es: ${{ steps.get-lambda-url.outputs.lambda_url}}"

      - name: Ejecutar Lambda v√≠a curl
        run: |
          echo "Invocando Lambda en ${{ steps.get-lambda-url.outputs.lambda_url }}"
          curl -X POST ${{ steps.get-lambda-url.outputs.lambda_url }}
